--------------------------------------------------------
--  File created - Tuesday-May-26-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SRC_SOCIALMEDIAPOST
--------------------------------------------------------

  CREATE TABLE "HR"."SRC_SOCIALMEDIAPOST" 
   (	"POST_ID" NUMBER, 
	"CAMPAIGN_ID" NUMBER, 
	"POST_CONTENT" VARCHAR2(500), 
	"PUBLISHED_DATE" DATE, 
	"POST_STATUS" VARCHAR2(50), 
	 PRIMARY KEY ("POST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
--------------------------------------------------------
--  DDL for Index SYS_C007061
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C007061" ON "HR"."SRC_SOCIALMEDIAPOST" ("POST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
--------------------------------------------------------
--  Constraints for Table SRC_SOCIALMEDIAPOST
--------------------------------------------------------

  ALTER TABLE "HR"."SRC_SOCIALMEDIAPOST" ADD PRIMARY KEY ("POST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
