--------------------------------------------------------
--  File created - Tuesday-May-26-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AUDIENCEINSIGHT
--------------------------------------------------------

  CREATE TABLE "HR"."AUDIENCEINSIGHT" 
   (	"INSIGHTID" NUMBER, 
	"CAMPAIGNID" NUMBER, 
	"AUDIENCECATEGORY" VARCHAR2(100), 
	"ENGAGEMENTSCORE" NUMBER(5,2), 
	"INSIGHTSTATUS" VARCHAR2(50), 
	 PRIMARY KEY ("INSIGHTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
--------------------------------------------------------
--  DDL for Index SYS_C007066
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C007066" ON "HR"."AUDIENCEINSIGHT" ("INSIGHTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
--------------------------------------------------------
--  Constraints for Table AUDIENCEINSIGHT
--------------------------------------------------------

  ALTER TABLE "HR"."AUDIENCEINSIGHT" ADD PRIMARY KEY ("INSIGHTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
