--------------------------------------------------------
--  File created - Tuesday-May-26-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SRC_CAMPAIGN
--------------------------------------------------------

  CREATE TABLE "STAGE"."SRC_CAMPAIGN" 
   (	"CAMPAIGN_ID" NUMBER, 
	"CAMPAIGN_NAME" VARCHAR2(200) NOT NULL ENABLE, 
	"PLATFORM_NAME" VARCHAR2(100), 
	"CAMPAIGN_BUDGET" NUMBER(12,2), 
	"CAMPAIGN_STATUS" VARCHAR2(50), 
	 PRIMARY KEY ("CAMPAIGN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007059
--------------------------------------------------------

  CREATE UNIQUE INDEX "STAGE"."SYS_C007059" ON "STAGE"."SRC_CAMPAIGN" ("CAMPAIGN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  Constraints for Table SRC_CAMPAIGN
--------------------------------------------------------

  ALTER TABLE "STAGE"."SRC_CAMPAIGN" ADD PRIMARY KEY ("CAMPAIGN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "STAGE"."SRC_CAMPAIGN" MODIFY ("CAMPAIGN_NAME" NOT NULL ENABLE)
