--------------------------------------------------------
--  File created - Tuesday-May-26-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TGT_CAMPAIGNALERT
--------------------------------------------------------

  CREATE TABLE "STAGE"."TGT_CAMPAIGNALERT" 
   (	"ALERTID" NUMBER, 
	"CAMPAIGNID" NUMBER, 
	"ALERTREASON" VARCHAR2(255), 
	"ALERTSEVERITY" VARCHAR2(50), 
	"ALERTSTATUS" VARCHAR2(50), 
	 PRIMARY KEY ("ALERTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007069
--------------------------------------------------------

  CREATE UNIQUE INDEX "STAGE"."SYS_C007069" ON "STAGE"."TGT_CAMPAIGNALERT" ("ALERTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  Constraints for Table TGT_CAMPAIGNALERT
--------------------------------------------------------

  ALTER TABLE "STAGE"."TGT_CAMPAIGNALERT" ADD PRIMARY KEY ("ALERTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
